image: ntwrkguru/pandoc-gitlab-ci

stages:
  - build

build:
  stage: build
  script:
     - pandoc Contents/Seminarinhalte.md -o Seminarinhalte.html
     - pandoc -s Contents/Seminarinhalte.md -o Seminarinhalte.pdf
     - pdflatex IntroDataScience/Handout-IntroDataScience.tex
     - pdflatex IntroDataScience/Slides-IntroDataScience.tex
     - pdflatex IntroPythonJupyter/Handout-IntroPythonJupyter.tex
     - pdflatex IntroPythonJupyter/Slides-IntroPythonJupyter.tex
     - pdflatex AIMethods/Handout-AIMethods.tex
     - pdflatex AIMethods/Slides-AIMethods.tex
     - pdflatex WebApp/Handout-WebApp.tex
     - pdflatex WebApp/Slides-WebApp.tex
     - pdflatex Numerics/Handout-Numerics.tex
     - pdflatex Textprocessing/Handout-TextProcessing.tex
     - pdflatex RareEvent/Handout-RareEvent.tex
     - pdflatex ObjectDetection/Handout-ObjectDetection.tex
     - pdflatex MonteCarlo/Handout-MonteCarlo.tex
     - pdflatex ImageProcessing/Handout-ImageProcessing.tex
     - pdflatex Exploration/Handout-Exploration.tex
     - pdflatex DynamicalSystems/Handout-DynamicalSystems.tex
     - pdflatex Datastructures/Handout-Datastructures.tex
     - pdflatex Datastructures/Handout-Pandas.tex
  artifacts:
    paths:
       - "*.html"
       - "*.pdf"
  tags:
    - shared-default