image: ntwrkguru/pandoc-gitlab-ci

stages:
  - build

build:
  stage: build
  script:
     - cd Intro
     - pandoc -s Seminarinhalte.md Seminarinhalte.html
     - pandoc Seminarinhalte.md Seminarinhalte.pdf
  artifacts:
    paths:
       - "*.html"
       - "*.pdf"
  tags:
    - shared-default