image: ntwrkguru/pandoc-gitlab-ci

stages:
  - build

build:
  stage: build
  script:
     - pandoc Contents/Seminarinhalte.md -o Seminarinhalte.html
     - pandoc -s Contents/Seminarinhalte.md -o Seminarinhalte.pdf
  artifacts:
    paths:
       - "*.html"
       - "*.pdf"
  tags:
    - shared-default