image: ntwrkguru/pandoc-gitlab-ci

stages:
  - build

build:
  stage: build
  script:
     - pandoc Contents/Seminarinhalte.md -o Seminarinhalte.html
     - pandoc -s Contents/Seminarinhalte.md -o Seminarinhalte.pdf
     - pdflatex IntroDataScience/Handout-IntroDataScience.tex
     - pdflatex IntroDataScience/Slides-IntroDataScience.tex
     - pdflatex IntroPythonJupyter/Handout-IntroPythonJupyter.tex
     - pdflatex IntroPythonJupyter/Slides-IntroPythonJupyter.tex
     - pdflatex AIMethods/Handout-AIMethods.tex
     - pdflatex AIMethods/Slides-AIMethods.tex
  artifacts:
    paths:
       - "*.html"
       - "*.pdf"
  tags:
    - shared-default