image: ntwrkguru/pandoc-gitlab-ci

stages:
  - build

build:
  stage: build
  script:
     - pandoc -s Intro/*.md -o *.html
     - pandoc -s Intro/*.md -o *.pdf
  artifacts:
    paths:
       - "*.html"
       - "*.pdf"
  tags:
    - shared-default